### ISSUE TITLE
updated packages not on load-path; deleted packages not removed from load-path

### ISSUE THREAD

**Issue by ryantm** [mola-T/SPU#4]
I'm really happy this package exists; thanks for making it! I have this issue that I haven't tracked down carefully, but I wanted to post here as a data point in case other people have this issue. It seems like sometimes randomly packages on my emacs installation will become unavailable. For example, `magit-mode` will suddenly be missing/not installed in the runtime. I think it is happening when SPU updates the packages, but I haven't carefully tracked it down. I'm not totally sure it is even caused by SPU, but I don't remember this kind of problem happening before I started using SPU. Restarting emacs always fixes the issue.

Is anyone else having a similar problem?

**Comment by mola-T** [comment]
em..... It might due to the change of `load-path`.

You can try reloading the `load-path` instead of restarting emacs:

```
(setq load-path nil) ;; reset load path
(let ((default-directory  "~/.emacs.d/lisp/"))
  (normal-top-level-add-subdirs-to-load-path)) ;; reload load-path, you may have different method of locating the load-path, use your own code instead
```

If this help, I can update the package.

**Comment by ryantm** [comment]
Thanks; I'll try that next time the problem occurs!

**Comment by ryantm** [comment]
Ah, yes. I just had the problem with haskell-mode. My load path contains the path of the old haskell-mode:

```
SPU Packages Upgrade Report - 09:27:56

Package                  Version            Operation   Status
haskell-mode             20160719.1434      Install     Succeeded
haskell-mode             20160719.451       Delete      Succeeded

load-path: (... "/home/ryantm/.emacs.d/elpa/haskell-mode-20160719.451/" ...)
```

and it does not contain the new haskell-mode.

I tried doing 

```
(setq load-path nil)

(let ((default-directory  "~/.emacs.d/elpa/"))
  (normal-top-level-add-subdirs-to-load-path))
```

but the load path remains nil after executing the second expression. When I try to do `M-h f` on `normal-top-level-add-subdirs-to-load-path` it says in `*Messages*`

```
run-hook-with-args: Cannot open load file: no such file or directory, eieio-opt
```

So I suspect clearing the load path might be causing problems with the second expression. As usual, restart emacs fixes it.

My emacs dotfiles are here: https://github.com/ryantm/dotfiles/tree/master/emacs/.emacs.d

**Comment by ryantm** [comment]
I think the reason this might not be an always-occurring problem is because it only happens to packages that are on the load path, but haven't been loaded. For example, I just ran the SPU upgrade manually on my computer and it updated the haskell-mode package, but it is still fine running haskell-mode. I think this happened because I already was using haskell-mode so it was already loaded and didn't need to load it again.

**Comment by mola-T** [comment]
Instead of this code,

```
(setq load-path nil)

(let ((default-directory  "~/.emacs.d/elpa/"))
  (normal-top-level-add-subdirs-to-load-path))
```

Can you try this if problem happen?

```
(setq load-path (list (file-name-as-directory
                       (concat user-emacs-directory "elpa")))
      normal-top-level-add-subdirs-inode-list nil)

(let ((default-directory (file-name-as-directory
                          (concat user-emacs-directory "elpa"))))
  (normal-top-level-add-subdirs-to-load-path))
```

The change include:
`load-path` is not set to `nil`, but your top level emas user directory.
`normal-top-level-add-subdirs-inode-list` is a variable I found from the source code of `normal-top-level-add-subdirs-to-load-path`. It stored the inode list for directories that have loaded. Clearing it allows `normal-top-level-add-subdirs-to-load-path` to run again.

I tested this code personally and is successful to reload the `load-path`.
I am not sure whether this help solving the problem.

**Comment by ryantm** [comment]
I had the problem again, this time with flycheck-mode. Your code does update the load path to have the correct new path for flycheck-mode but `M-x flycheck-mode` gives `byte-code: Cannot open load file: no such file or directory, rx`.

**Comment by ryantm** [comment]
I'm not sure what is going on, but I haven't encountered this problem lately, even though the circumstances are pretty much the same. I'm closing it for now.
